ng_main_homepage:
    path:     /
    defaults: { _controller: NGMainBundle:Main:index }
ng_main_aboutus:
    path:     /a-propos-de-nous
    defaults: { _controller: NGMainBundle:Main:about }
ng_main_contact:
    path:     /contactez-nous
    defaults: { _controller: NGMainBundle:Main:contact }

ng_main_solution_erp:
    path:     /solutions-erp
    defaults: { _controller: NGMainBundle:Main:solutions }

ng_main_solutions_web:
    path:     /solutions-web
    defaults: { _controller: NGMainBundle:Main:solutions_web}

ng_main_solutions_mobiles:
    path:     /solutions-mobiles
    defaults: { _controller: NGMainBundle:Main:solutions_mobiles}

ng_main_service_audit_conseil:
     path:     /service-audit-conseil
     defaults: { _controller: NGMainBundle:Main:service_audit_conseil}

ng_main_service_suivi_formation:
      path:     /service-suivi-formation
      defaults: { _controller: NGMainBundle:Main:service_suivi_formation}